openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-gcp-cloud-sql-mysql
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              vpc_id: string                  # the ID of the VPC where the MySQL service applies
              kms_key_id: string,optional     # the ID of the KMS key which to encrypt the MySQL data
              domain_suffix: string,optional  # a private DNS namespace of the PrivateZone where to register the applied MySQL service
              publicly_accessible: bool       # whether the MySQL service is publicly accessible
            ```
          default:
            publicly_accessible: true
          properties:
            domain_suffix:
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            kms_key_id:
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            publicly_accessible:
              default: false
              title: Publicly Accessible
              type: boolean
              x-walrus-ui:
                order: 4
            vpc_id:
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://cloud.google.com/sql/docs/db-versions.
          default: "8.0"
          enum:
          - "8.0"
          - "5.7"
          - "5.6"
          x-walrus-ui:
            group: Basic
            order: 4
        database:
          title: Database
          type: string
          description: |
            Specify the database name. The database name must be 1-60 characters long and start with any lower letter, combined with number, or symbols: - _.
            The database name cannot be MySQL forbidden keyword.
          default: mydb
          x-walrus-ui:
            group: Basic
            order: 5
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 1-32 characters long and start with lower letter, combined with number.
            The username cannot be MySQL forbidden keyword and azure_superuser, admin, administrator, root, guest or public.
          default: rdsuser
          x-walrus-ui:
            group: Basic
            order: 6
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be more than 8-128 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          writeOnly: true
          minLength: 8
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 7
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
            The computing resource design of Google Cloud is very complex, it also needs to consider on the storage resource, please view the specification document for more information.

            Examples:
            ```
            resources:
              class: string, optional            # https://cloud.google.com/sql/docs/mysql/instance-settings
            ```
          default:
            class: db-g1-small
          properties:
            class:
              default: db-g1-small
              description: |
                Specify the instance tier.
                See # https://cloud.google.com/sql/docs/mysql/instance-settings
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources, select from PD_SSD or PD_HDD.
            Choosing the storage resource is also related to the computing resource, please view the specification document for more information.

            Examples:
            ```
            storage:
              class: string, optional        # https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#disk_type
              size: number, optional         # in megabyte
            ```
          default:
            class: PD_SSD
            size: 10240
          properties:
            class:
              default: PD_SSD
              description: |
                Specify the disk type.
              enum:
              - "PD_SSD"
              - "PD_HDD"
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              default: 10240
              description: |
                Specify the disk size. Unit is megabyte.
              minimum: 10240
              title: Size
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
      x-walrus-ui:
        groupOrder:
        - Basic
